export const CURATED_ICONS = [
  "rocket",
  "target",
  "folder",
  "briefcase",
  "code",
  "bug",
  "zap",
  "star",
  "heart",
  "flag",
  "bookmark",
  "clipboard",
  "layers",
  "database",
  "globe",
  "shield",
  "lock",
  "key",
  "settings",
  "wrench",
  "lightbulb",
  "megaphone",
  "calendar",
  "clock",
  "users",
  "mail",
  "message-circle",
  "file-text",
  "image",
  "palette",
  "truck",
  "shopping-cart",
  "trending-up",
  "music",
  "gamepad-2",
  // Communication
  "phone",
  "video",
  "at-sign",
  "send",
  // Development
  "terminal",
  "git-branch",
  "git-merge",
  "cpu",
  "server",
  "cloud",
  "wifi",
  "hard-drive",
  // Documents
  "file",
  "folder-open",
  "archive",
  "notebook",
  "book-open",
  "scroll",
  "newspaper",
  // Nature / Weather
  "sun",
  "moon",
  "cloud-rain",
  "flame",
  "leaf",
  "tree-pine",
  // Navigation
  "compass",
  "map",
  "map-pin",
  "navigation",
  "signpost",
  // Objects
  "gift",
  "package",
  "scissors",
  "tag",
  "paperclip",
  "pin",
  // People / Social
  "user-check",
  "user-plus",
  "thumbs-up",
  // Finance
  "wallet",
  "credit-card",
  "coins",
  "piggy-bank",
  // Science
  "flask-conical",
  "microscope",
  "atom",
  "dna",
  "brain",
  // Misc
  "sparkles",
  "bell",
  // Status / Progress
  "check-circle",
  "alert-triangle",
  "circle-dot",
  "hourglass",
  // Analytics / Charts
  "bar-chart-2",
  "pie-chart",
  "activity",
  "gauge",
  // Business / Work
  "trophy",
  "crown",
  "presentation",
  "building-2",
  "handshake",
  // Creative / Media
  "camera",
  "film",
  "headphones",
  "mic",
  "pen-tool",
  "brush",
  // Education / Writing
  "graduation-cap",
  "pencil",
  "book-marked",
  // Tech / Devices
  "laptop",
  "monitor",
  "smartphone",
  "link",
  "qr-code",
  // Essentials
  "home",
  "search",
  "eye",
  "coffee",
  "hammer",
  "refresh-cw",
  // Transport
  "plane",
  "car",
  // Healthcare / Medical
  "stethoscope",
  "heart-pulse",
  "syringe",
  "pill",
  "hospital",
  // Legal / Compliance
  "scale",
  "gavel",
  "file-check",
  // HR / People Ops
  "user-round",
  "contact",
  "badge-check",
  "id-card",
  // Construction / Physical Ops
  "hard-hat",
  "ruler",
  "warehouse",
  "fence",
  // Food / Hospitality
  "utensils",
  "chef-hat",
  "store",
  "receipt",
  // Sustainability / Environment
  "recycle",
  "wind",
  "droplets",
  "earth",
  // Security / Infosec
  "scan",
  "fingerprint-pattern",
  "shield-alert",
  "radar",
  // Accessibility / Inclusion
  "accessibility",
  "ear",
  "hand",
  // Workflow / Process
  "workflow",
  "git-pull-request",
  "kanban",
  "repeat",
  "split",
  "merge",
] as const;

export type CuratedIconName = (typeof CURATED_ICONS)[number];
