import {
  Activity,
  AlertTriangle,
  Archive,
  Atom,
  AtSign,
  BarChart2,
  Bell,
  Bookmark,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calendar,
  Camera,
  Car,
  CheckCircle,
  CircleDot,
  Clipboard,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dna,
  Eye,
  File,
  FileText,
  Film,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderOpen,
  Gamepad2,
  Gauge,
  Gift,
  GitBranch,
  GitMerge,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  Home,
  Hourglass,
  Image,
  Key,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  Lock,
  type LucideIcon,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Music,
  Navigation,
  Newspaper,
  Notebook,
  Package,
  Palette,
  Paperclip,
  Pencil,
  PenTool,
  Phone,
  PieChart,
  PiggyBank,
  Pin,
  Plane,
  Presentation,
  QrCode,
  RefreshCw,
  Rocket,
  Scissors,
  Scroll,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Signpost,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  UserCheck,
  UserPlus,
  Users,
  Video,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Static mapping from curated icon names (kebab-case) to their lucide-react components.
 * This keeps the icon set bounded and avoids dynamic imports.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  rocket: Rocket,
  target: Target,
  folder: Folder,
  briefcase: Briefcase,
  code: Code,
  bug: Bug,
  zap: Zap,
  star: Star,
  heart: Heart,
  flag: Flag,
  bookmark: Bookmark,
  clipboard: Clipboard,
  layers: Layers,
  database: Database,
  globe: Globe,
  shield: Shield,
  lock: Lock,
  key: Key,
  settings: Settings,
  wrench: Wrench,
  lightbulb: Lightbulb,
  megaphone: Megaphone,
  calendar: Calendar,
  clock: Clock,
  users: Users,
  mail: Mail,
  "message-circle": MessageCircle,
  "file-text": FileText,
  image: Image,
  palette: Palette,
  truck: Truck,
  "shopping-cart": ShoppingCart,
  "trending-up": TrendingUp,
  music: Music,
  "gamepad-2": Gamepad2,
  // Communication
  phone: Phone,
  video: Video,
  "at-sign": AtSign,
  send: Send,
  // Development
  terminal: Terminal,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  cpu: Cpu,
  server: Server,
  cloud: Cloud,
  wifi: Wifi,
  "hard-drive": HardDrive,
  // Documents
  file: File,
  "folder-open": FolderOpen,
  archive: Archive,
  notebook: Notebook,
  "book-open": BookOpen,
  scroll: Scroll,
  newspaper: Newspaper,
  // Nature / Weather
  sun: Sun,
  moon: Moon,
  "cloud-rain": CloudRain,
  flame: Flame,
  leaf: Leaf,
  "tree-pine": TreePine,
  // Navigation
  compass: Compass,
  map: Map,
  "map-pin": MapPin,
  navigation: Navigation,
  signpost: Signpost,
  // Objects
  gift: Gift,
  package: Package,
  scissors: Scissors,
  tag: Tag,
  paperclip: Paperclip,
  pin: Pin,
  // People / Social
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "thumbs-up": ThumbsUp,
  // Finance
  wallet: Wallet,
  "credit-card": CreditCard,
  coins: Coins,
  "piggy-bank": PiggyBank,
  // Science
  "flask-conical": FlaskConical,
  microscope: Microscope,
  atom: Atom,
  dna: Dna,
  brain: Brain,
  // Misc
  sparkles: Sparkles,
  bell: Bell,
  // Status / Progress
  "check-circle": CheckCircle,
  "alert-triangle": AlertTriangle,
  "circle-dot": CircleDot,
  hourglass: Hourglass,
  // Analytics / Charts
  "bar-chart-2": BarChart2,
  "pie-chart": PieChart,
  activity: Activity,
  gauge: Gauge,
  // Business / Work
  trophy: Trophy,
  crown: Crown,
  presentation: Presentation,
  "building-2": Building2,
  handshake: Handshake,
  // Creative / Media
  camera: Camera,
  film: Film,
  headphones: Headphones,
  mic: Mic,
  "pen-tool": PenTool,
  brush: Brush,
  // Education / Writing
  "graduation-cap": GraduationCap,
  pencil: Pencil,
  "book-marked": BookMarked,
  // Tech / Devices
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  link: Link,
  "qr-code": QrCode,
  // Essentials
  home: Home,
  search: Search,
  eye: Eye,
  coffee: Coffee,
  hammer: Hammer,
  "refresh-cw": RefreshCw,
  // Transport
  plane: Plane,
  car: Car,
};

/**
 * Resolves a curated icon name to its lucide-react component.
 * Returns null for unknown or empty names so callers can render a fallback.
 */
export function getIconComponent(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return ICON_MAP[name] ?? null;
}
